---
title: "RFI_alphaclean"
author: "Andrew Zavala"
date: "9/14/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set Up

```{r Global Options, message=FALSE, warning=FALSE}
library(tidyverse); library(ggthemes); library(rio); library(lsr)
```

```{r, Graphics Tuner}

line_size = 2.3
leftFrame_col = "royalblue"
rightFrame_col = "firebrick2"
upFrame_col = "grey24"
text_size = 22 
colour <- c("royalblue", "firebrick2")

```

# Import Data

```{r Import data, warning=FALSE, message=FALSE}
setwd("/Users/MarekFirestone/Desktop/Repos/PRD Lab/Alpha/subjects")
files <- list.files()
data_raw <- NULL

for(i in 1:length(files)){
  
  data_raw <- import(paste0(files[i]),
                     na.strings = c("NULL")) %>% 
    mutate(sid = i) %>%
    rbind(data_raw)
}
```

# Housekeeping

```{r Housekeeping}

# data_raw > alpha_data

alpha_data <- data_raw %>%  
  janitor::clean_names() %>%
  filter(trial_type == "real") %>% 
  select(sid, everything()) %>% 
  arrange(sid) %>%
  mutate(
    probe_del_ms = round(probe_del * (16 + 2/3), 0),
    
    frame_orient = ifelse(frame_tilt == "-15", "Left", "Right"),
    
    stair_approach = ifelse(substr(trial_variant,2,2) == "L", "Left", "Right"),
    
    alpha_condition = ifelse(alpha_entrain_refreshes == 5, "Fast", "Slow"),
    
    alpha_condition = as.factor(alpha_condition))

# Filter Reversals

data_pse1 <- alpha_data %>%
  filter(reversal_num > 6,
         reversal == 1)

# Calculate PSE (with averages and without)

data_pse1 <- data_pse1 %>%
  group_by(sid, frame_orient, probe_del_ms, alpha_condition) %>% 
  summarise(pse = mean(rod_tilt))
```

# Check if 6 reversals from 2 to 8 is enough instead of all 12

```{r}

# Check if 6 reversals is enough to get the effect

data_rev <- alpha_data %>%
  filter(reversal_num > 2 & reversal_num < 8,
         reversal == 1)

data_rev_clean <- data_rev %>%
  group_by(sid, frame_orient, probe_del_ms, alpha_condition) %>%
  summarise(pse = mean(rod_tilt))

write.csv(data_rev_clean, file = "/Users/MarekFirestone/Desktop/Repos/PRD Lab/Alpha/data_rev_clean.csv")

```

# Plot data_pse

```{r}

data_pse_avg <- data_pse1 %>%
  group_by(frame_orient, probe_del_ms, alpha_condition) %>%
  summarize(mean_pse = mean(pse),
            se_pse = sd(pse) / sqrt(length(files)))

# Plot

plot_LR_frames <- data_pse_avg %>% 
  ggplot(aes(probe_del_ms, mean_pse, color = frame_orient)) +
  geom_vline(xintercept = 0, col = "grey29", linetype = 3, size = line_size) +
  geom_line(aes(linetype = alpha_condition), size = line_size) +
  geom_errorbar(aes(ymin = mean_pse - se_pse, ymax = mean_pse + se_pse),
                width = 1.4, size = 1.4, 
                position = "dodge") + 
  geom_point(shape = 21, size = 6, fill = "white") +
  ylab(expression(paste("PSE (",degree,")"))) +
  theme_bw() +
  theme(axis.title = element_text(size = text_size))  +
  theme(axis.title.x = element_blank()) +
  theme(axis.text = element_text(size = text_size)) +
  scale_colour_manual(values=colour) 

plot_LR_frames

```

# Calculate data_rfe

```{r}

data_rfe <- data_pse1 %>%
  unite(frame_col, "frame_orient", "alpha_condition") %>% 
  spread(frame_col, pse) %>% 
  mutate(Fast = Right_Fast - Left_Fast,
         Slow = Right_Slow - Left_Slow) %>%
  select(sid, probe_del_ms, Fast, Slow) %>% 
  gather(alpha, rfe, -c(sid, probe_del_ms)) %>%
  arrange(sid)

```

# Group-level descriptives

```{r}
data_rfe_desc <- data_rfe %>%
  group_by(sid) %>%
  summarize(rfe = mean(rfe)) %>%
  mutate(sub = as.factor(sid))

vector <- data_rfe_desc %>%
  arrange(rfe) %>%
  select(sub)

vector <- as.vector(vector)

reorder(data_rfe_desc$sub, vector)

data_rfe_desc %>%
ggplot(aes(sub, rfe, color = sub)) +
  geom_point(show.legend = FALSE) +
  theme_minimal()

```



# Compare rod_tilt avgs between data_rt and data_pse

```{r}
data_rfe
data_rt

data_rt_check <- data_rt %>%
  filter(sid == 1) %>%
  group_by(probe_del_ms, alpha_condition) %>%
  summarize(mean(rfe))

data_rfe_check <- data_rfe %>%
  filter(sid == 1) %>%
  group_by(probe_del_ms, alpha)

data_rt_checkall <- data_rt %>%
  group_by(probe_del_ms, alpha_condition) %>%
  summarize(mean(rfe))

data_rfe_checkall <- data_rfe %>%
  group_by(probe_del_ms, alpha) %>%
  summarize(mean(rfe))

```

# Repeated Measures Analysis

```{r}
# use data_pse and subtract left from right

library(lme4)
library(lmerTest)

# With interaction
model_1 <- lmer(rfe ~ alpha + probe_del_ms + alpha*probe_del_ms + (1 | sid),
     data = data_rfe)
anova(model_1)

# Without accounting for interaction

model_2 <- lmer(rfe ~ alpha + probe_del_ms + (1 | sid),
     data = data_rfe)
anova(model_2)

# Including the Frames (multiplying by -1 for left)

data_left <- data_pse1 %>%
  filter(frame_orient == "Left") %>%
  mutate(pse = (pse*-1))

data_right <- data_pse1 %>%
  filter(frame_orient == "Right")

data_pse_inverse <- rbind(data_left, data_right)

data_pse_inverse <- data_pse_inverse %>%
  select(-frame_orient)

data_pse_inverse <- data_pse_inverse[,2:5]

data_pse_inverse <- data_pse_inverse %>%
  mutate(sid = as.factor(sid),
         probe_del_ms = as.factor(probe_del_ms))

model_3 <- lmer(pse ~  probe_del_ms + alpha_condition + probe_del_ms*alpha_condition + (1 | sid), data = data_pse_inverse)
anova(model_3)
summary(model_3)

data_rfe %>%
  group_by(probe_del_ms, alpha) %>%
  summarise(mean(rfe)) %>%
  View

```

# Plot RFE

```{r}

# Cell Means

plot_RFE <- data_rfe %>%
  select(sid, alpha, probe_del_ms, rfe) %>% 
  unnest() %>% 
  group_by(alpha, probe_del_ms) %>%
  summarize(mean_rfe = mean(rfe),
            se_rfe = sd(rfe) / sqrt(length(files)))

plot_RFE

```


```{r}
# Make some graphs
# Using data_pse

data_desc <- data_pse1 %>%
  select(sid, probe_del_ms, alpha_condition, frame_orient, rod_tilt)

for (i in 1:nrow(data_desc)) {
  if (data_desc$frame_orient[i] == "Left") {
    data_desc$rod_tilt[i] = data_desc$rod_tilt[i]*-1
  }
}

data_desc <- data_desc %>%
  select(-frame_orient)

data_desc <- data_desc %>%
  mutate(probe_del_ms = as.factor(probe_del_ms),
         sid = as.factor(sid))

# Cell Means

data_desc %>%
  group_by(probe_del_ms, alpha_condition) %>%
  summarise(rod_tilt = mean(rod_tilt)) %>%
  View

#%>%
 # ggplot(aes(alpha_condition, rod_tilt, color = alpha_condition)) +
  #geom_point(show.legend = FALSE, size = 3) +
  #facet_wrap(~probe_del_ms) +
  #theme_minimal() +
  #ylab("Illusion Magnitude") +
  #xlab("Alpha Condition")

# Subject Means

data_desc %>%
  group_by(sid, probe_del_ms, alpha_condition) %>%
  summarise(rod_tilt = mean(rod_tilt)) %>%
  ggplot(aes(rod_tilt, group = probe_del_ms, color = probe_del_ms)) +
  geom_density() +
  facet_wrap(~alpha_condition) +
  theme_minimal() +
  xlab("Rod Tilt (˚)")



alpha_model <- lmer(rod_tilt ~ alpha_condition + probe_del_ms + alpha_condition*probe_del_ms + (1 | sid),
     data = data_desc)
anova(alpha_model)

```

```{r}
# Plot stuff using data_rfe

data_rfe[alpha == "Fast"] <- "12 Hz"

trend_all <- data_rfe %>%
  mutate(alpha = replace(alpha, alpha == "Slow", "8.66"),
         alpha = replace(alpha, alpha == "Fast", "12"),
         alpha = as.factor(alpha),
         alpha = relevel(alpha, "8.66")) %>%
  group_by(sid, probe_del_ms, alpha) %>%
  summarize(rfe = mean(rfe)) %>%
  ggplot() +
  geom_line(aes(alpha, rfe, group = as.factor(sid), color = as.factor(sid)), show.legend = FALSE) +
  facet_wrap(~probe_del_ms) +
  xlab("Alpha Frequency (Hz)") +
  ylab("Illusion Magnitude (˚)") +
  ggtitle("Individual Illusion Magnitude by Alpha Frequency") +
  theme_minimal() +
  theme(plot.title = element_text(size = 20, hjust = 0.5))

trend_all



```
